### ISSUE TITLE
Errors deploying on EKS

### ISSUE THREAD

**Issue by kbarresi** [streamnative/charts#115] opened 2020-07-15 21:55 UTC
Hello,

We've used this chart to deploy Pulsar locally without issue, in a `kind` k8s cluster (version 0.8.1) with persistence. However, when we deploy the same configuration to EKS, we run into issues, specifically with PVCs. We are using Kubernetes version 1.15, and Helm 2.14.0.

We're correctly seeing the volumes being created (e.g. `pulsar-bookie-{journal,ledgers}-pulsar-bookie-{0..2} `). However, several pods are having issues with messages such as this being repeated, and the bookies never being ready:

```
pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 node(s) had taints that the pod didn't tolerate, 1 node(s) had no available volume zone
```

Our EKS cluster currently operates in 2 availability zones. We tried disabling anti-affinity, but it had no impact.

Any advice would be greatly appreciated!

**Comment by sijie** [comment] 2020-07-16 08:14
@kbarresi How did you disable the anti-affinity?

**Comment by sijie** [comment] 2020-07-17 09:04
@kbarresi 

The Kubernetes scheduler does not handle zone constraints when using dynamic provisioning of zone-specific storage - such as for example EBS. First, the PersistentVolumeClaim is created and it is only then that the volume binding / dynamic provisioning occurs. This can lead to unexpected behavior where the PVC is created in a zone where there are actually no resources available for scheduling the pod.

We need to change the volume binding mode for fixing the issue.

**Comment by kbarresi** [comment] 2020-07-28 19:37
@sijie - as a work-around, we found that modifying our standard storage class's `volumeBindingMode` from `Immediate` to `WaitForFirstConsumer`  fixed this issue:

```yaml
volumeBindingMode: WaitForFirstConsumer
```

One potential solution that could be added to the chart would be giving the option to specify storage classes.

**Comment by sijie** [comment] 2020-07-28 20:11
@kbarresi Yeah. We have added the functionality to the chart in #124

**Comment by austince** [comment] 2020-07-28 20:55
@sijie please correct me if I'm wrong -- it looks like you've added more ways to customize the storage classes created by this chart (nice!) but there still doesn't seem to be a way to specify an existing storage class to use other than `standard`. I think this would be a more natural fit for many users. For us, we have defined a set of "standard" storage classes and would not like to create new ones, especially because they can have some pretty serious cost differences.

**Comment by austince** [comment] 2020-07-28 20:58
Ah, look at that: https://github.com/streamnative/charts/issues/126

**Comment by sijie** [comment] 2020-07-28 21:16
@austince Yeah, #126 is for adding the capability.

**Comment by sijie** [comment] 2020-08-04 07:21
both #124 and #126 have been merged. Closed this issue now.

**Closed by sijie** 2020-08-04 07:21 UTC
Labels: triage/week-29, workflow::todo
